# Generated by Django 4.1.3 on 2023-03-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crash_event", "0002_event_delete_crashevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("REPORT_NUMBER", models.IntegerField()),
                ("VEHICLE_NUMBER", models.IntegerField()),
                ("PERSON_NUMBER", models.IntegerField()),
                ("INJURY_SEVERITY", models.CharField(max_length=100)),
                ("SEX", models.CharField(max_length=1)),
                ("AGE", models.IntegerField()),
                ("RESTRAINT_SYSTEMS", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("REPORT_NUMBER", models.IntegerField()),
                ("VEHICLE_NUMBER", models.IntegerField()),
                ("YEAR", models.IntegerField()),
                ("MAKE", models.CharField(max_length=100)),
                ("MODEL", models.CharField(max_length=100)),
                ("COLOR", models.CharField(max_length=100)),
                ("TRAVELING_ON_STREET", models.CharField(max_length=1000)),
                ("TRAVELING_DIRECTION", models.CharField(max_length=1000)),
                ("MANEUVER", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="event",
            name="CITY",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="event",
            name="COUNTY",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="event",
            name="CRASH_SEVERITY",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="event",
            name="INVESTIGATING_AGENCY",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="event",
            name="OFFSET_DIRECTION",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
